
-- MySql version
CREATE TABLE DAILY_TASKS (
    TASK_ID     INT(10) UNSIGNED PRIMARY KEY,
    TASK_NAME     VARCHAR(225) NOT NULL,
    DESCRIPTION   VARCHAR(500) NOT NULL,
    TASK_TIME     TIME NOT NULL,
    PROJECT       VARCHAR(225) NOT NULL,
    DEPTID        INT(10) UNSIGNED NOT NULL,
    ALLOCATED_TIME INT(10) UNSIGNED NOT NULL,
    WEEK_NUMBER   INT(10) UNSIGNED NOT NULL,
    DATE          DATE NOT NULL,
    DAY_NUM       INT(10) UNSIGNED NOT NULL,
    WEEKLY_NOTE   VARCHAR(500) NOT NULL
);
CREATE TABLE PROJECTS (
    PROJECT_ID INT(10) UNSIGNED PRIMARY KEY,
    PROJECT_NAME VARCHAR(225) NOT NULL,
    PROJECT_DESCRIPTION VARCHAR(500) NOT NULL,
    DATE DATE NOT NULL,
    STATUS VARCHAR(225) NOT NULL
);